name: Test
on:
  push:
    branches:
      - main
      - "*.x"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: v4-yarn-cache-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run Jest
        run: yarn jest
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
